// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: commons.proto

package com.sdqube.entities;

public final class CommonsPb {
  private CommonsPb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code sdqube.entities.pb.ErrorCode}
   */
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *Just default value for enum in proto. Should not be used as error code.
     * </pre>
     *
     * <code>UNKNOWN_ERROR = 0;</code>
     */
    UNKNOWN_ERROR(0),
    /**
     * <pre>
     *When any required input is null.
     * </pre>
     *
     * <code>NPE = 4;</code>
     */
    NPE(4),
    /**
     * <pre>
     *Mostly used with validation check.
     * </pre>
     *
     * <code>ILLEGAL = 5;</code>
     */
    ILLEGAL(5),
    /**
     * <pre>
     *For duplicate records.
     * </pre>
     *
     * <code>DUPLICATE = 6;</code>
     */
    DUPLICATE(6),
    /**
     * <pre>
     *When any action fails. Like while saving record on db
     * </pre>
     *
     * <code>FAILED = 7;</code>
     */
    FAILED(7),
    /**
     * <pre>
     *When records are not found.
     * </pre>
     *
     * <code>NOTFOUND = 8;</code>
     */
    NOTFOUND(8),
    /**
     * <pre>
     *For invalid inputs.
     * </pre>
     *
     * <code>INVALID = 9;</code>
     */
    INVALID(9),
    /**
     * <pre>
     *For any runtime exception
     * </pre>
     *
     * <code>EXCEPTION = 10;</code>
     */
    EXCEPTION(10),
    /**
     * <pre>
     *For timeouts on calling any third party services
     * </pre>
     *
     * <code>TIMEOUT = 11;</code>
     */
    TIMEOUT(11),
    /**
     * <pre>
     *If authorization failed
     * </pre>
     *
     * <code>AUTH_ERROR = 12;</code>
     */
    AUTH_ERROR(12),
    /**
     * <pre>
     *If user don't have permission
     * </pre>
     *
     * <code>PERMISSION_ERROR = 13;</code>
     */
    PERMISSION_ERROR(13),
    /**
     * <pre>
     *If user don't have permission
     * </pre>
     *
     * <code>FORBIDDEN = 14;</code>
     */
    FORBIDDEN(14),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *Just default value for enum in proto. Should not be used as error code.
     * </pre>
     *
     * <code>UNKNOWN_ERROR = 0;</code>
     */
    public static final int UNKNOWN_ERROR_VALUE = 0;
    /**
     * <pre>
     *When any required input is null.
     * </pre>
     *
     * <code>NPE = 4;</code>
     */
    public static final int NPE_VALUE = 4;
    /**
     * <pre>
     *Mostly used with validation check.
     * </pre>
     *
     * <code>ILLEGAL = 5;</code>
     */
    public static final int ILLEGAL_VALUE = 5;
    /**
     * <pre>
     *For duplicate records.
     * </pre>
     *
     * <code>DUPLICATE = 6;</code>
     */
    public static final int DUPLICATE_VALUE = 6;
    /**
     * <pre>
     *When any action fails. Like while saving record on db
     * </pre>
     *
     * <code>FAILED = 7;</code>
     */
    public static final int FAILED_VALUE = 7;
    /**
     * <pre>
     *When records are not found.
     * </pre>
     *
     * <code>NOTFOUND = 8;</code>
     */
    public static final int NOTFOUND_VALUE = 8;
    /**
     * <pre>
     *For invalid inputs.
     * </pre>
     *
     * <code>INVALID = 9;</code>
     */
    public static final int INVALID_VALUE = 9;
    /**
     * <pre>
     *For any runtime exception
     * </pre>
     *
     * <code>EXCEPTION = 10;</code>
     */
    public static final int EXCEPTION_VALUE = 10;
    /**
     * <pre>
     *For timeouts on calling any third party services
     * </pre>
     *
     * <code>TIMEOUT = 11;</code>
     */
    public static final int TIMEOUT_VALUE = 11;
    /**
     * <pre>
     *If authorization failed
     * </pre>
     *
     * <code>AUTH_ERROR = 12;</code>
     */
    public static final int AUTH_ERROR_VALUE = 12;
    /**
     * <pre>
     *If user don't have permission
     * </pre>
     *
     * <code>PERMISSION_ERROR = 13;</code>
     */
    public static final int PERMISSION_ERROR_VALUE = 13;
    /**
     * <pre>
     *If user don't have permission
     * </pre>
     *
     * <code>FORBIDDEN = 14;</code>
     */
    public static final int FORBIDDEN_VALUE = 14;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ErrorCode valueOf(int value) {
      return forNumber(value);
    }

    public static ErrorCode forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN_ERROR;
        case 4: return NPE;
        case 5: return ILLEGAL;
        case 6: return DUPLICATE;
        case 7: return FAILED;
        case 8: return NOTFOUND;
        case 9: return INVALID;
        case 10: return EXCEPTION;
        case 11: return TIMEOUT;
        case 12: return AUTH_ERROR;
        case 13: return PERMISSION_ERROR;
        case 14: return FORBIDDEN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrorCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.sdqube.entities.CommonsPb.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorCode[] VALUES = values();

    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ErrorCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:sdqube.entities.pb.ErrorCode)
  }

  public interface DebugOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sdqube.entities.pb.Debug)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string debugId = 1;</code>
     */
    java.lang.String getDebugId();
    /**
     * <code>string debugId = 1;</code>
     */
    com.google.protobuf.ByteString
        getDebugIdBytes();

    /**
     * <code>string locale = 4;</code>
     */
    java.lang.String getLocale();
    /**
     * <code>string locale = 4;</code>
     */
    com.google.protobuf.ByteString
        getLocaleBytes();

    /**
     * <code>string appVersion = 6;</code>
     */
    java.lang.String getAppVersion();
    /**
     * <code>string appVersion = 6;</code>
     */
    com.google.protobuf.ByteString
        getAppVersionBytes();
  }
  /**
   * Protobuf type {@code sdqube.entities.pb.Debug}
   */
  public  static final class Debug extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sdqube.entities.pb.Debug)
      DebugOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Debug.newBuilder() to construct.
    private Debug(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Debug() {
      debugId_ = "";
      locale_ = "";
      appVersion_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Debug(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              debugId_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              locale_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              appVersion_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sdqube.entities.CommonsPb.internal_static_sdqube_entities_pb_Debug_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sdqube.entities.CommonsPb.internal_static_sdqube_entities_pb_Debug_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sdqube.entities.CommonsPb.Debug.class, com.sdqube.entities.CommonsPb.Debug.Builder.class);
    }

    public static final int DEBUGID_FIELD_NUMBER = 1;
    private volatile java.lang.Object debugId_;
    /**
     * <code>string debugId = 1;</code>
     */
    public java.lang.String getDebugId() {
      java.lang.Object ref = debugId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        debugId_ = s;
        return s;
      }
    }
    /**
     * <code>string debugId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDebugIdBytes() {
      java.lang.Object ref = debugId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        debugId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCALE_FIELD_NUMBER = 4;
    private volatile java.lang.Object locale_;
    /**
     * <code>string locale = 4;</code>
     */
    public java.lang.String getLocale() {
      java.lang.Object ref = locale_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        locale_ = s;
        return s;
      }
    }
    /**
     * <code>string locale = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLocaleBytes() {
      java.lang.Object ref = locale_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        locale_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPVERSION_FIELD_NUMBER = 6;
    private volatile java.lang.Object appVersion_;
    /**
     * <code>string appVersion = 6;</code>
     */
    public java.lang.String getAppVersion() {
      java.lang.Object ref = appVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string appVersion = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAppVersionBytes() {
      java.lang.Object ref = appVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDebugIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, debugId_);
      }
      if (!getLocaleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, locale_);
      }
      if (!getAppVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, appVersion_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDebugIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, debugId_);
      }
      if (!getLocaleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, locale_);
      }
      if (!getAppVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, appVersion_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sdqube.entities.CommonsPb.Debug)) {
        return super.equals(obj);
      }
      com.sdqube.entities.CommonsPb.Debug other = (com.sdqube.entities.CommonsPb.Debug) obj;

      boolean result = true;
      result = result && getDebugId()
          .equals(other.getDebugId());
      result = result && getLocale()
          .equals(other.getLocale());
      result = result && getAppVersion()
          .equals(other.getAppVersion());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEBUGID_FIELD_NUMBER;
      hash = (53 * hash) + getDebugId().hashCode();
      hash = (37 * hash) + LOCALE_FIELD_NUMBER;
      hash = (53 * hash) + getLocale().hashCode();
      hash = (37 * hash) + APPVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getAppVersion().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sdqube.entities.CommonsPb.Debug parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sdqube.entities.CommonsPb.Debug parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sdqube.entities.CommonsPb.Debug parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sdqube.entities.CommonsPb.Debug parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sdqube.entities.CommonsPb.Debug parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sdqube.entities.CommonsPb.Debug parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sdqube.entities.CommonsPb.Debug parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sdqube.entities.CommonsPb.Debug parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sdqube.entities.CommonsPb.Debug parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sdqube.entities.CommonsPb.Debug parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sdqube.entities.CommonsPb.Debug parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sdqube.entities.CommonsPb.Debug parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sdqube.entities.CommonsPb.Debug prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sdqube.entities.pb.Debug}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sdqube.entities.pb.Debug)
        com.sdqube.entities.CommonsPb.DebugOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sdqube.entities.CommonsPb.internal_static_sdqube_entities_pb_Debug_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sdqube.entities.CommonsPb.internal_static_sdqube_entities_pb_Debug_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sdqube.entities.CommonsPb.Debug.class, com.sdqube.entities.CommonsPb.Debug.Builder.class);
      }

      // Construct using com.sdqube.entities.CommonsPb.Debug.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        debugId_ = "";

        locale_ = "";

        appVersion_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sdqube.entities.CommonsPb.internal_static_sdqube_entities_pb_Debug_descriptor;
      }

      @java.lang.Override
      public com.sdqube.entities.CommonsPb.Debug getDefaultInstanceForType() {
        return com.sdqube.entities.CommonsPb.Debug.getDefaultInstance();
      }

      @java.lang.Override
      public com.sdqube.entities.CommonsPb.Debug build() {
        com.sdqube.entities.CommonsPb.Debug result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sdqube.entities.CommonsPb.Debug buildPartial() {
        com.sdqube.entities.CommonsPb.Debug result = new com.sdqube.entities.CommonsPb.Debug(this);
        result.debugId_ = debugId_;
        result.locale_ = locale_;
        result.appVersion_ = appVersion_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sdqube.entities.CommonsPb.Debug) {
          return mergeFrom((com.sdqube.entities.CommonsPb.Debug)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sdqube.entities.CommonsPb.Debug other) {
        if (other == com.sdqube.entities.CommonsPb.Debug.getDefaultInstance()) return this;
        if (!other.getDebugId().isEmpty()) {
          debugId_ = other.debugId_;
          onChanged();
        }
        if (!other.getLocale().isEmpty()) {
          locale_ = other.locale_;
          onChanged();
        }
        if (!other.getAppVersion().isEmpty()) {
          appVersion_ = other.appVersion_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sdqube.entities.CommonsPb.Debug parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sdqube.entities.CommonsPb.Debug) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object debugId_ = "";
      /**
       * <code>string debugId = 1;</code>
       */
      public java.lang.String getDebugId() {
        java.lang.Object ref = debugId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          debugId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string debugId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDebugIdBytes() {
        java.lang.Object ref = debugId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          debugId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string debugId = 1;</code>
       */
      public Builder setDebugId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        debugId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string debugId = 1;</code>
       */
      public Builder clearDebugId() {
        
        debugId_ = getDefaultInstance().getDebugId();
        onChanged();
        return this;
      }
      /**
       * <code>string debugId = 1;</code>
       */
      public Builder setDebugIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        debugId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object locale_ = "";
      /**
       * <code>string locale = 4;</code>
       */
      public java.lang.String getLocale() {
        java.lang.Object ref = locale_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          locale_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string locale = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLocaleBytes() {
        java.lang.Object ref = locale_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          locale_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string locale = 4;</code>
       */
      public Builder setLocale(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        locale_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string locale = 4;</code>
       */
      public Builder clearLocale() {
        
        locale_ = getDefaultInstance().getLocale();
        onChanged();
        return this;
      }
      /**
       * <code>string locale = 4;</code>
       */
      public Builder setLocaleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        locale_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object appVersion_ = "";
      /**
       * <code>string appVersion = 6;</code>
       */
      public java.lang.String getAppVersion() {
        java.lang.Object ref = appVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string appVersion = 6;</code>
       */
      public com.google.protobuf.ByteString
          getAppVersionBytes() {
        java.lang.Object ref = appVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string appVersion = 6;</code>
       */
      public Builder setAppVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string appVersion = 6;</code>
       */
      public Builder clearAppVersion() {
        
        appVersion_ = getDefaultInstance().getAppVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string appVersion = 6;</code>
       */
      public Builder setAppVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appVersion_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sdqube.entities.pb.Debug)
    }

    // @@protoc_insertion_point(class_scope:sdqube.entities.pb.Debug)
    private static final com.sdqube.entities.CommonsPb.Debug DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sdqube.entities.CommonsPb.Debug();
    }

    public static com.sdqube.entities.CommonsPb.Debug getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Debug>
        PARSER = new com.google.protobuf.AbstractParser<Debug>() {
      @java.lang.Override
      public Debug parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Debug(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Debug> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Debug> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sdqube.entities.CommonsPb.Debug getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PermissionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sdqube.entities.pb.Permission)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string permissionId = 1;</code>
     */
    java.lang.String getPermissionId();
    /**
     * <code>string permissionId = 1;</code>
     */
    com.google.protobuf.ByteString
        getPermissionIdBytes();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>int64 createAt = 14;</code>
     */
    long getCreateAt();

    /**
     * <code>int64 updatedAt = 15;</code>
     */
    long getUpdatedAt();
  }
  /**
   * Protobuf type {@code sdqube.entities.pb.Permission}
   */
  public  static final class Permission extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sdqube.entities.pb.Permission)
      PermissionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Permission.newBuilder() to construct.
    private Permission(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Permission() {
      permissionId_ = "";
      name_ = "";
      createAt_ = 0L;
      updatedAt_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Permission(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              permissionId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 112: {

              createAt_ = input.readInt64();
              break;
            }
            case 120: {

              updatedAt_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sdqube.entities.CommonsPb.internal_static_sdqube_entities_pb_Permission_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sdqube.entities.CommonsPb.internal_static_sdqube_entities_pb_Permission_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sdqube.entities.CommonsPb.Permission.class, com.sdqube.entities.CommonsPb.Permission.Builder.class);
    }

    public static final int PERMISSIONID_FIELD_NUMBER = 1;
    private volatile java.lang.Object permissionId_;
    /**
     * <code>string permissionId = 1;</code>
     */
    public java.lang.String getPermissionId() {
      java.lang.Object ref = permissionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        permissionId_ = s;
        return s;
      }
    }
    /**
     * <code>string permissionId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPermissionIdBytes() {
      java.lang.Object ref = permissionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        permissionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATEAT_FIELD_NUMBER = 14;
    private long createAt_;
    /**
     * <code>int64 createAt = 14;</code>
     */
    public long getCreateAt() {
      return createAt_;
    }

    public static final int UPDATEDAT_FIELD_NUMBER = 15;
    private long updatedAt_;
    /**
     * <code>int64 updatedAt = 15;</code>
     */
    public long getUpdatedAt() {
      return updatedAt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getPermissionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, permissionId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (createAt_ != 0L) {
        output.writeInt64(14, createAt_);
      }
      if (updatedAt_ != 0L) {
        output.writeInt64(15, updatedAt_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getPermissionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, permissionId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (createAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(14, createAt_);
      }
      if (updatedAt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(15, updatedAt_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sdqube.entities.CommonsPb.Permission)) {
        return super.equals(obj);
      }
      com.sdqube.entities.CommonsPb.Permission other = (com.sdqube.entities.CommonsPb.Permission) obj;

      boolean result = true;
      result = result && getPermissionId()
          .equals(other.getPermissionId());
      result = result && getName()
          .equals(other.getName());
      result = result && (getCreateAt()
          == other.getCreateAt());
      result = result && (getUpdatedAt()
          == other.getUpdatedAt());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PERMISSIONID_FIELD_NUMBER;
      hash = (53 * hash) + getPermissionId().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + CREATEAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateAt());
      hash = (37 * hash) + UPDATEDAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdatedAt());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sdqube.entities.CommonsPb.Permission parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sdqube.entities.CommonsPb.Permission parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sdqube.entities.CommonsPb.Permission parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sdqube.entities.CommonsPb.Permission parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sdqube.entities.CommonsPb.Permission parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sdqube.entities.CommonsPb.Permission parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sdqube.entities.CommonsPb.Permission parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sdqube.entities.CommonsPb.Permission parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sdqube.entities.CommonsPb.Permission parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sdqube.entities.CommonsPb.Permission parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sdqube.entities.CommonsPb.Permission parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sdqube.entities.CommonsPb.Permission parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sdqube.entities.CommonsPb.Permission prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sdqube.entities.pb.Permission}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sdqube.entities.pb.Permission)
        com.sdqube.entities.CommonsPb.PermissionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sdqube.entities.CommonsPb.internal_static_sdqube_entities_pb_Permission_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sdqube.entities.CommonsPb.internal_static_sdqube_entities_pb_Permission_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sdqube.entities.CommonsPb.Permission.class, com.sdqube.entities.CommonsPb.Permission.Builder.class);
      }

      // Construct using com.sdqube.entities.CommonsPb.Permission.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        permissionId_ = "";

        name_ = "";

        createAt_ = 0L;

        updatedAt_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sdqube.entities.CommonsPb.internal_static_sdqube_entities_pb_Permission_descriptor;
      }

      @java.lang.Override
      public com.sdqube.entities.CommonsPb.Permission getDefaultInstanceForType() {
        return com.sdqube.entities.CommonsPb.Permission.getDefaultInstance();
      }

      @java.lang.Override
      public com.sdqube.entities.CommonsPb.Permission build() {
        com.sdqube.entities.CommonsPb.Permission result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sdqube.entities.CommonsPb.Permission buildPartial() {
        com.sdqube.entities.CommonsPb.Permission result = new com.sdqube.entities.CommonsPb.Permission(this);
        result.permissionId_ = permissionId_;
        result.name_ = name_;
        result.createAt_ = createAt_;
        result.updatedAt_ = updatedAt_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sdqube.entities.CommonsPb.Permission) {
          return mergeFrom((com.sdqube.entities.CommonsPb.Permission)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sdqube.entities.CommonsPb.Permission other) {
        if (other == com.sdqube.entities.CommonsPb.Permission.getDefaultInstance()) return this;
        if (!other.getPermissionId().isEmpty()) {
          permissionId_ = other.permissionId_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getCreateAt() != 0L) {
          setCreateAt(other.getCreateAt());
        }
        if (other.getUpdatedAt() != 0L) {
          setUpdatedAt(other.getUpdatedAt());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sdqube.entities.CommonsPb.Permission parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sdqube.entities.CommonsPb.Permission) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object permissionId_ = "";
      /**
       * <code>string permissionId = 1;</code>
       */
      public java.lang.String getPermissionId() {
        java.lang.Object ref = permissionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          permissionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string permissionId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPermissionIdBytes() {
        java.lang.Object ref = permissionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          permissionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string permissionId = 1;</code>
       */
      public Builder setPermissionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        permissionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string permissionId = 1;</code>
       */
      public Builder clearPermissionId() {
        
        permissionId_ = getDefaultInstance().getPermissionId();
        onChanged();
        return this;
      }
      /**
       * <code>string permissionId = 1;</code>
       */
      public Builder setPermissionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        permissionId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private long createAt_ ;
      /**
       * <code>int64 createAt = 14;</code>
       */
      public long getCreateAt() {
        return createAt_;
      }
      /**
       * <code>int64 createAt = 14;</code>
       */
      public Builder setCreateAt(long value) {
        
        createAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 createAt = 14;</code>
       */
      public Builder clearCreateAt() {
        
        createAt_ = 0L;
        onChanged();
        return this;
      }

      private long updatedAt_ ;
      /**
       * <code>int64 updatedAt = 15;</code>
       */
      public long getUpdatedAt() {
        return updatedAt_;
      }
      /**
       * <code>int64 updatedAt = 15;</code>
       */
      public Builder setUpdatedAt(long value) {
        
        updatedAt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 updatedAt = 15;</code>
       */
      public Builder clearUpdatedAt() {
        
        updatedAt_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sdqube.entities.pb.Permission)
    }

    // @@protoc_insertion_point(class_scope:sdqube.entities.pb.Permission)
    private static final com.sdqube.entities.CommonsPb.Permission DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sdqube.entities.CommonsPb.Permission();
    }

    public static com.sdqube.entities.CommonsPb.Permission getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Permission>
        PARSER = new com.google.protobuf.AbstractParser<Permission>() {
      @java.lang.Override
      public Permission parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Permission(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Permission> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Permission> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sdqube.entities.CommonsPb.Permission getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdqube_entities_pb_Debug_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sdqube_entities_pb_Debug_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sdqube_entities_pb_Permission_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sdqube_entities_pb_Permission_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcommons.proto\022\022sdqube.entities.pb\"<\n\005D" +
      "ebug\022\017\n\007debugId\030\001 \001(\t\022\016\n\006locale\030\004 \001(\t\022\022\n" +
      "\nappVersion\030\006 \001(\t\"U\n\nPermission\022\024\n\014permi" +
      "ssionId\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\020\n\010createAt\030" +
      "\016 \001(\003\022\021\n\tupdatedAt\030\017 \001(\003*\273\001\n\tErrorCode\022\021" +
      "\n\rUNKNOWN_ERROR\020\000\022\007\n\003NPE\020\004\022\013\n\007ILLEGAL\020\005\022" +
      "\r\n\tDUPLICATE\020\006\022\n\n\006FAILED\020\007\022\014\n\010NOTFOUND\020\010" +
      "\022\013\n\007INVALID\020\t\022\r\n\tEXCEPTION\020\n\022\013\n\007TIMEOUT\020" +
      "\013\022\016\n\nAUTH_ERROR\020\014\022\024\n\020PERMISSION_ERROR\020\r\022" +
      "\r\n\tFORBIDDEN\020\016B#\n\023com.sdqube.entitiesB\tC" +
      "ommonsPb\240\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sdqube_entities_pb_Debug_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sdqube_entities_pb_Debug_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sdqube_entities_pb_Debug_descriptor,
        new java.lang.String[] { "DebugId", "Locale", "AppVersion", });
    internal_static_sdqube_entities_pb_Permission_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sdqube_entities_pb_Permission_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sdqube_entities_pb_Permission_descriptor,
        new java.lang.String[] { "PermissionId", "Name", "CreateAt", "UpdatedAt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
